# Generated by Django 2.2 on 2021-12-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
